const ADD_TRANSACTION = 'ADD_TRANSACTION';
const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';
const CHANGE_EXCHANGE_RATE = 'CHANGE_EXCHANGE_RATE';

export default {
	ADD_TRANSACTION,
	REMOVE_TRANSACTION,
	CHANGE_EXCHANGE_RATE
}
